name: flutter_cool_morning
description: "Cool morning mobile app remade with flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  persistent_bottom_nav_bar_v2: ^5.2.3
  #flutter_pdfview: ^1.3.2
  path_provider: ^2.1.3
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Gotham
      fonts:
        - asset: fonts/gotham_ultra.otf

    - family: Gothic
      fonts:
        - asset: fonts/GOTHIC.ttf
        - asset: fonts/GOTHICB.ttf